name: Add Contributor

on:
    pull_request:
        types: [closed]
        branches:
            - main

jobs:
    add-contributor:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "14.x"
            - name: Add Contributor
              env:
                  GITHUB_TOKEN: ${{ secrets.TOKEN }}
              run: |
                  @all-contributors please add @${{ github.event.pull_request.user.login }} for code
                  git add README.md
                  git commit -m "Add @${{ github.event.pull_request.user.login }} as a contributor"
                  git push
